### PR TITLE
fix wrong sign info

### PR DESCRIPTION
**Pull request by rachpt**
之前的匹配到了 注释行，如下图：
https://imgchr.com/i/Q5wUFx

另外我最近在使用 pyqt5 配合该api写一个 gui 版本。 😀

### CODE REVIEW

**Comment by guorenn** [comment]
import requests

class LanZouCloud(object):

    def __init__(self):
        self._account_url = 'https://up.woozooo.com/mlogin.php'
        
        
    def login(self, username, passwd):
        """登录蓝奏云控制台"""
        login_data = {"formhash": "002b2898", "task": "3", "uid": username, "pwd": passwd}
        response = requests.post(self._account_url, login_data)
        html = response.json()["info"]
        cookie = requests.utils.dict_from_cookiejar(response.cookies)
        return [html,cookie]

            
            
            
if __name__ == "__main__":
    app = LanZouCloud()
    print(app.login(username,password))

**Comment by guorenn** [comment]
`
import requests

class LanZouCloud(object):

    def __init__(self):
        self._account_url = 'https://up.woozooo.com/mlogin.php'
        
        
    def login(self, username, passwd):
        """登录蓝奏云控制台"""
        login_data = {"formhash": "002b2898", "task": "3", "uid": username, "pwd": passwd}
        response = requests.post(self._account_url, login_data)
        html = response.json()["info"]
        cookie = requests.utils.dict_from_cookiejar(response.cookies)
        return [html,cookie]

            
            
            
if __name__ == "__main__":
    app = LanZouCloud()
    print(app.login(username,password))`

**Comment by guorenn** [comment]
`

    import requests

    class LanZouCloud(object):

        def __init__(self):
            self._account_url = 'https://up.woozooo.com/mlogin.php'
        
        
        def login(self, username, passwd):
            """登录蓝奏云控制台"""
            login_data = {"formhash": "002b2898", "task": "3", "uid": username, "pwd": passwd}
            response = requests.post(self._account_url, login_data)
            html = response.json()["info"]
            cookie = requests.utils.dict_from_cookiejar(response.cookies)
            return [html,cookie]

            
            
            
    if __name__ == "__main__":
        app = LanZouCloud()
        print(app.login(username,password))

`

**Comment by guorenn** [comment]
实际上可以通过安卓的蓝奏云app抓包 跳过滑动验证

**Comment by zaxtyson** [comment]
不好意思，因为期末的缘故一直没看github，刚想修复来着，谢啦

**Comment by zzpg001** [comment]
怎么获取Cookie？有没有一键获取？

**Pull request merged**
